apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ng-mtools
  template:
    metadata:
      labels:
        app: ng-mtools
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80
        - name: multitool
          image: wbitt/network-multitool
          env:
          - name: HTTP_PORT
            value: "8080" 
---
apiVersion: v1
kind: Service
metadata:
  name: ng-mtools-svc
spec:
  selector:
    app: ng-mtools
  ports:
  - name: nginx-listener
    protocol: TCP
    port: 9001
    targetPort: 80
  - name: multitool-listener
    protocol: TCP
    port: 9002
    targetPort: 8080
