apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  selector:
    app: ng-mtools
  ports:
  - name: nginx-listener
    port: 80
    targetPort: 80
    nodePort: 30007
  - name: multitool-listener
    port: 8080
    targetPort: 8080
    nodePort: 30008
  type: NodePort
