apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-reader
  labels:
    app: log-reader
spec:
  selector:
    matchLabels:
      app: log-reader
      type: daemonset
  template:
    metadata:
      labels:
        app: log-reader
        type: daemonset
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: logs-volume
              mountPath: /host_logs
              readOnly: true
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/log
            type: Directory
