apiVersion: v1
kind: Service
metadata:
  name: deploy-svc
spec:
  selector:
    app: nginx-multitool
  ports:
  - name: nginx-listener
    port: 8080
    protocol: TCP
    targetPort: 80
  - name: multitool-port
    port: 8081
    protocol: TCP
    targetPort: 1180
