apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-nginx
  template:
    metadata:
      labels:
        app: deploy-nginx
    spec:
      containers:
        - name: deploy-nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80
      initContainers:
        - name    : delay
          image   : busybox:latest
          command: ['sleep', '30']
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-nginx-svc
spec:
  selector:
    app: deploy-nginx
  ports:
  - name: nginx-listener
    port: 8080
    protocol: TCP
    targetPort: 80
