apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
    <head>
      <title>Welcome to Nginx!!!!</title>
    </head>
    <body>
      <h1>Homework for the lesson "Application Configuration"</h1>
    </body>
    </html>
