---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: local-pv
